Feature/menu
paulidan/resposive-web pull request #5
Opened 2022-07-07 10:14 UTC by ssmolenn

2022-07-07 10:31 UTC, Mateusz-N approved these changes, later dismissed
Ok, zatwierdzam

2022-07-10 11:10 UTC, mwilczek-net requested changes
Wywalić niepotrzebne pliki. Przenieść zmiany do reacta. I będzie ok 😄

2022-07-10 11:10 UTC, mwilczek-net commented on .vscode/settings.json
> +}
Podobnie jak w: https://github.com/paulidan/resposive-web/pull/7#discussion_r917378316

2022-07-10 11:10 UTC, mwilczek-net commented on index.html
> +        <meta name="viewport" content="width=device-width, initial-scale=1">
Ten plik powinien wylecieć -> przechodzimy na reacta

2022-07-10 11:10 UTC, mwilczek-net commented on main.css
> +top:646px;
Ten plik tak jak `index.html` powinien wylecieć. Zmiany powinny być przeniesione do reacta.

2022-07-11 10:08 UTC, mwilczek-net approved these changes

2022-07-11 10:13 UTC, merged